### ISSUE TITLE
About CZ2 files

### ISSUE THREAD

**Issue by hvpexe** [wetor/LuckSystem#10]
Hello, I understand that Lucksystem currently does not support decompressing cz2 files due to some issues your team is facing. However, it's sad that the Loopers (Steam) uses this cz2 format for fonts, and the project may postpone if this font type cannot be decompressed.

I thought that you are quite busy, so I researched on my own. In the end, I went down a similar dead-end as you: **the images in the cz2 file are compressed using the lzw algorithm with some modifications, and it's quite peculiar**.

Below is my analysis (please note that I'm not specialized in reverse engineering):
- Taking the example of the file 明朝32, the compressed image data starts from offset 446h. I noticed that _almost_ UInt16 values after that are **even numbers**
![image](https://github.com/wetor/LuckSystem/assets/97070754/8d97a7a8-9684-45b4-87c8-94326723c09a)

 - So I made adjustments to the lzw algorithm in [LucaSystemTool](https://github.com/wetor/LucaSystemTools) (I used the old tool because it already had a base implementation for cz2) as follows:
![image](https://github.com/wetor/LuckSystem/assets/97070754/4395c594-98ac-4589-92c7-b8b9e7f46a2d)
![image](https://github.com/wetor/LuckSystem/assets/97070754/340c6404-4db2-4f5a-b1e2-56d3857c6828)
- And this is result:
![明朝32](https://github.com/wetor/LuckSystem/assets/97070754/e21a2f83-7bec-46c6-bee8-8d6e690a53d9)
- I believe this chaos begins at offset 102ECh, at which point Uint16 has a value of 159, which is the first odd value. This corresponds to the 32595th value in the List<UInt16> compressed. At this stage, I can't think of anything else to overcome the issue.

You may have thoroughly understood the analysis I raised above but haven't been able to resolve it yet. I hope that some day in the future, your team can discover a decompressed mechanism for this file type.
PS: this is font [明朝32.zip](https://github.com/wetor/LuckSystem/files/13463342/32.zip)

**Comment by wetor** [comment]
After debugging, it was found that the index of the dictionary was not simply shifted one bit to the right (divided by 2), but it was even before 32595 without encountering any problems. However, an error occurred in the calculated index afterwards, resulting in LZW decompression error

uint16 159  (32595 th)  Correct: 32847
uint16 11361 (32596 th)  Correct: 8902
uint16 30274 (32597 th)  Correct: 14180
uint16 52883 (32598 th)  Correct: 15593
...
The correct data corresponding to these few bytes: 
![image](https://github.com/wetor/LuckSystem/assets/29877452/0e328836-5faf-49c6-8a19-a4b0ade73388)
The logic is probably here: 
![image](https://github.com/wetor/LuckSystem/assets/29877452/97d3e759-9839-4c20-a146-30aee1a858ab)


I think I can solve this problem as soon as today, otherwise it will be solved next weekend

**Comment by hvpexe** [comment]
Thank you so much, hoping you will successfully compress and decompress this file.

**Comment by wetor** [comment]
You can try using CZ0 or CZ1 format fonts (obtained and edited from other games). I remember we tested it before, and as long as the font size and corresponding info file are correct, regardless of the image format, they can be used normally


Regarding CZ2, there has been some progress in extraction, but there are still issues that may not be resolved in the short term. It is also impossible to achieve import before the extraction is complete. You should prioritize using self-made fonts in other formats

**Comment by hvpexe** [comment]
Actually, I have read your [blog](https://blog.wetorx.cn/posts/LucaSystemTools/) and discovered above method. Then we used cz1 with correct size to replace font.pak, and the results are not very promising. 
![image](https://github.com/wetor/LuckSystem/assets/97070754/4d03bfbb-388c-41cf-ae06-808827dcfc2e)

We will try testing further with cz0 by trial and error. 
PS: The default font size dialog text is 44 for English.

**Comment by wetor** [comment]
I thought for a moment, and if I don't succeed after trying CZ2 again, I will give up.

For Windows, using hooks is a simpler and more efficient method. Based on my research on CZ2, I think I can try implementing a hook program to directly load PNG image fonts

**Comment by wetor** [comment]
https://github.com/wetor/LuckSystem/commit/604e858fc5a731d901fcb790671849d6f31e1bde

https://github.com/wetor/LuckSystem/releases/tag/v2.1.0

The extraction of CZ2 has been completed, but the code has not been optimized yet. The compression part may not be implemented temporarily.


Afterwards, I will try to replace the runtime font image with a hook method

The executable files of this game may have some compression and cannot be easily decompiled, so I spent a lot of time dynamically debugging and manually implementing the assembly code. For me, this is an interesting attempt

**Comment by hvpexe** [comment]
Wow, this is really a challenging work, truly appreciate your efforts. 
Looking forward to the results you will achieve in the next commits.
