### ISSUE TITLE
CartagraHD images

### ISSUE THREAD

**Issue by OneSeri** [wetor/LuckSystem#18]
Many images do not want to export
![image](https://github.com/user-attachments/assets/d5a48642-73b5-4d0c-8ac1-c05c34b051ae)
For example, "CAUTION_BG" is exported normally, but "CAUTION_TEXT" does not want to be exported.
![image](https://github.com/user-attachments/assets/27ea6bb6-b282-4caf-97a8-816e2f5f49ac)

**Comment by thedanill** [comment]
If you open the specified image in any hex editor, you will find that it is encoded in cz4 format:
<img width="567" alt="image" src="https://github.com/user-attachments/assets/49d41576-bab1-4e4b-9430-9217194bbee9">
The repository description says that this format is not currently supported.
The easiest way is to use other utilities such as G2-Games/lbee-utils or wetor/LucaSystemTools.

**Comment by OneSeri** [comment]
спасибо
