### ISSUE TITLE
Need help with Opcode- from Vietnam Key Fanclub

### ISSUE THREAD

**Issue by TooNakko** [wetor/LuckSystem#8]
Hi!

I'm here representing [Vietnam Key Fanclub](https://github.com/vnkeyfc) and [Minata Hatsune](https://github.com/minatahatsune) to open an issue regarding our problems with LuckSystem. 

We are currently doing a patch for [Loopers](https://store.steampowered.com/app/1811500/LOOPERS/) Steam version, and we are in trouble with the Script extracting because of opcode.txt. We tried to do something with your [opcode tool](https://github.com/wetor/LucaSystemTools/tree/6954d5f20f94f872b3c13987a39e2fbe94d71824/LucaSystemTools/OpcodeGuide), following the steps written in there but we couldn't make it. 

So we hope that your team can give us a more detailed, clear guide about how to use that tool, and it will help us so much if you can provide something like videos recording the process or a careful step by step guide since we are all amateurs about coding stuff.

Sincerely thanks for your kind offer of assistance.

**Comment by wetor** [comment]
For this project, opcode.txt requires a simple decompilation of the game's executable file, which I can provide assistance with. You only need to upload the game's executable file.

The most important thing is that you need to modify the code to achieve corresponding game support

I am unable to provide assistance in programming because I do not have this game and do not have enough time.

If there are any bugs in the basic code of this project, I am happy to fix them

**Comment by wetor** [comment]
[LOOPERS_OPCODE.txt](https://github.com/wetor/LuckSystem/files/12429936/LOOPERS_OPCODE.txt)

![image](https://github.com/wetor/LuckSystem/assets/29877452/c256f2da-257a-4a14-92d4-558a9340fcf2)

Looking forward to your pull request

**Comment by wetor** [comment]
By the way, for the export and import of scripts, please refer to the following code: 
https://github.com/wetor/LuckSystem/blob/master/main_test.go

 Alternatively, you can try using LucaSystemTools.

**Comment by TooNakko** [comment]
Thanks for your help!
We will work with the file you provided and contact you later.
And we understand your lack of time. We won't abuse your willingness to help so don't worry.

**Comment by wetor** [comment]
https://github.com/wetor/LuckSystem/releases/tag/v2.0.0

Currently, LOOPERS scripts have perfect support for modification (can exceed the original string length)

Currently, this tool has completely decompiled the script, although it has not implemented true compilation, it supports "import" based on source scripts.

It should be noted that the decompiled script should only make textual modifications as much as possible. Modifying the game's logic and values may lead to unexpected errors!

It is recommended to write additional programs to modify the decompiled text to prevent misoperation

If there is a bug in the program, please contact us via email, which can be in Chinese or English

email: wetorx@qq.com
