### ISSUE TITLE
Cannot decompile script because something wrong in python file

### ISSUE THREAD

**Issue by hvpexe** [wetor/LuckSystem#9]
This is an error I encountered while decompiling the script, and it appears to be a Python file issue. Specifically, it cannot find the base.loopers library.
![image](https://github.com/wetor/LuckSystem/assets/97070754/2a316c27-0f06-443f-b66c-4dfa6b4d7538)

I noticed that the .gitignore file has excluded library file from the repository. I hope you can push them up.
![image](https://github.com/wetor/LuckSystem/assets/97070754/0d0b39e5-8f3c-420a-8548-059cfdc7330b)
Honestly, I don't have experience with Python nor Golang, so if there are any my mistakes, please correct me.
Thank you.

**Comment by wetor** [comment]
You are right, this is my negligence. I will fix this problem in about four or five hours

**Comment by wetor** [comment]
Uploaded, you can directly download the release
https://github.com/wetor/LuckSystem/releases

**Comment by hvpexe** [comment]
> Uploaded, you can directly download the release https://github.com/wetor/LuckSystem/releases

Thank you so much, it worked

**Comment by hvpexe** [comment]
by the way, there is a small bug in your scriptImport, you should change it to VMRunImport
![image](https://github.com/wetor/LuckSystem/assets/97070754/38c8f799-03a5-4921-a0ec-a70158962b37)

**Comment by wetor** [comment]
Fixed, thank you
https://github.com/wetor/LuckSystem/releases/tag/v2.0.3

**Comment by hvpexe** [comment]
thanks, close issue
